[project]
name = "cactro-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "pymupdf>=1.26.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.3",
]
